routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\ProfilUserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\CommentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontController::class,'home'])->name('home');

Route::middleware('auth')->group(function () {
    Route::get('/artikel/{judul}/{id}',[FrontController::class,'show'])->name('front.show');

    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

    Route::get('/dashboard/user/{id}/profile/edit', [ProfilUserController::class, 'edit'])->name('profil.edit')->middleware();

    Route::post('/dashboard/user/{id}/profile/edit', [ProfilUserController::class, 'store'])->name('profil.store');

    Route::put('/dashboard/user/{id}/profile/edit', [ProfilUserController::class, 'update'])->name('profil.update');
    Route::post('/artikel/{judul}/{id}',[CommentController::class,'store'])->name('komen.store');

/*    Route::get('/comments',[CommentController::class,'index'])->name('comments.index');
    Route::get('/comments/create',[CommentController::class,'showCreateForm'])->name('comments.create');*/



});



Route::get('/coba', function () {
   return view('layouts.admin-lte.master');
});

Auth::routes();
Route::get('/profil/user/edit', [ProfilUserController::class, 'edit']);
/*Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');*/
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::resource('/post', 'PostController');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = "posts";
    protected $fillable = ["judul", "isi"];
    use HasFactory;
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function comments()
    {
        return $this->belongsToMany('App\Models\Comment');
    }

    public function user2(){
        return $this->hasOneThrough('App\Models\User','App\Models\Comment');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post = Post::where('user_id',Auth::id())->get();
        $statusPosting = 'active';
        return view('post.index', compact('post','statusPosting'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = new Post;
        $post->judul = $request->judul;
        $post->isi = $request->isi;
        $post->created_at = now();
        $post->updated_at = now();
        $post->user_id = Auth::id();
        $post->save();
        return Redirect('/post')->with('pesan', 'Diposting');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return view('post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        return view('post.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'isi' => 'required',
            'judul' => 'required',
        ]);

        $post = Post::find($id);
        $post->judul = $request->judul;
        $post->isi = $request->isi;
        $post->update();
        return redirect('/post')->with('pesan','Diperbarui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $post->delete();
        return redirect('/post')->with('pesan','Dihapus');
    }
}

resources/views/post/create.blade.php
@extends('layouts.admin-lte.master')
@push('scripts-head')
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush
@section('content')

<form action="{{route('post.store')}}" method="POST">
    @csrf
    <div class="form-group">
        <label for="judul">Judul</label>
        <input type="text" class="form-control" name="judul" id="judul" placeholder="Masukkan Judul">
        @error('judul')
            <div class="alert alert-danger">
                {{ $message }}
            </div>
        @enderror
    </div>
    <div class="form-group">
        <label for="isi">Isi</label>
        <textarea name="isi" class="form-control my-editor">{!! old('isi', $isi ?? '') !!}</textarea>
        @error('isi')
            <div class="alert alert-danger">
                {{ $message }}
            </div>
        @enderror
    </div>
    <button type="submit" class="btn btn-primary">Tambah</button>
</form>
</div>

@endsection
@push('script')
<script>
    var editor_config = {
      path_absolute : "/",
      selector: "textarea.my-editor",
      plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
      ],
      toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
      relative_urls: false,
      file_browser_callback : function(field_name, url, type, win) {
        var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
        var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;
  
        var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
        if (type == 'image') {
          cmsURL = cmsURL + "&type=Images";
        } else {
          cmsURL = cmsURL + "&type=Files";
        }
  
        tinyMCE.activeEditor.windowManager.open({
          file : cmsURL,
          title : 'Filemanager',
          width : x * 0.8,
          height : y * 0.8,
          resizable : "yes",
          close_previous : "no"
        });
      }
    };
  
    tinymce.init(editor_config);
  </script>
@endpush

resources/views/post/edit.blade.php
@extends('layouts.admin-lte.master')
@push('scripts-head')
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush
@section('content')
<div>
    <h2>Edit Post {{$post->id}}</h2>
    <form action="/post/{{$post->id}}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="judul">Judul</label>
            <input type="text" class="form-control" name="judul" value="{{$post->judul}}" id="judul" placeholder="Masukkan Title">
            @error('judul')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label for="isi">Isi</label>
            <textarea name="isi" class="form-control my-editor">{!! old('isi', $post->isi ?? '') !!}</textarea>
            @error('isi')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>
</div>
@endsection
@push('script')
<script>
    var editor_config = {
      path_absolute : "/",
      selector: "textarea.my-editor",
      plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
      ],
      toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
      relative_urls: false,
      file_browser_callback : function(field_name, url, type, win) {
        var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
        var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

        var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
        if (type == 'image') {
          cmsURL = cmsURL + "&type=Images";
        } else {
          cmsURL = cmsURL + "&type=Files";
        }

        tinyMCE.activeEditor.windowManager.open({
          file : cmsURL,
          title : 'Filemanager',
          width : x * 0.8,
          height : y * 0.8,
          resizable : "yes",
          close_previous : "no"
        });
      }
    };

    tinymce.init(editor_config);
  </script>
@endpush

resources/views/post/index.blade.php
@extends('layouts.admin-lte.master')
@section('content')


<section class="content">
    <div class="container-fluid">
        <a href="/post/create" class="btn btn-primary mb-3">Buat Postingan</a>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card">
                            <div class="card-header">
                                <h3 class="card-title"><b>Postingan</b></h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Judul</th>
                                    <th>Tanggal Diposting</th>
                                    <th>Aksi</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($post as $item)
                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td>{{str::words($item->judul,6)}}</td>
                                        <td>{{date('d-m-Y',strtotime($item->created_at))}}</td>
                                        <td class="d-md-inline-block">
                                            <a href="/post/{{$item->id}}/edit" class="btn btn-warning">Edit</a>
                                            <a href="{{route('front.show',['judul'=>str::slug($item->judul,'-'),'id'=>$item->id])}}" class="btn btn-info">Lihat</a>
                                            <div class="d-md-inline-block">
                                                <form action="/post/{{$item->id}}" method="post" class="">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" id="modalButton" class="btn btn-danger" onclick="return confirm('Apakah yakin akan dihapus?')" data-toggle="modal" data-target="#modalHapus" data-id="">Hapus</a>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->

                        <!-- Modal -->
                       {{-- <div class="modal fade" id="modalHapus" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Peringatan!!!</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Apakah anda yakin ingin menghapus data ini?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                                        <form action="" id="deleteForm" method="post">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-danger">Ya</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>--}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('script')

    @if(session('pesan') !='')
        <script !src="">
            swal({
                title: "Berhasil!",
                text: "Artikel Berhasil {{session('pesan')}}",
                icon: "success",
                button: "Ok",
            });</script>
        @php
            session()->forget('notif');
        @endphp
    @endif
@endpush

resources/views/post/show.blade.php
@extends('layouts.admin-lte.master')
@section('content')
<h2>Show Post {{$post->id}}</h2>
<h4>{{$post->judul}}</h4>
<p>{{$post->isi}}</p>    
@endsection