routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\ProfilUserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\CommentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontController::class,'home'])->name('home');

Route::middleware('auth')->group(function () {
    Route::get('/artikel/{judul}/{id}',[FrontController::class,'show'])->name('front.show');

    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

    Route::get('/dashboard/user/{id}/profile/edit', [ProfilUserController::class, 'edit'])->name('profil.edit')->middleware();

    Route::post('/dashboard/user/{id}/profile/edit', [ProfilUserController::class, 'store'])->name('profil.store');

    Route::put('/dashboard/user/{id}/profile/edit', [ProfilUserController::class, 'update'])->name('profil.update');
    Route::post('/artikel/{judul}/{id}',[CommentController::class,'store'])->name('komen.store');

/*    Route::get('/comments',[CommentController::class,'index'])->name('comments.index');
    Route::get('/comments/create',[CommentController::class,'showCreateForm'])->name('comments.create');*/



});



Route::get('/coba', function () {
   return view('layouts.admin-lte.master');
});

Auth::routes();
Route::get('/profil/user/edit', [ProfilUserController::class, 'edit']);
/*Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');*/
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::resource('/post', 'PostController');

app/Models/ProfilUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProfilUser extends Model
{
    use HasFactory;
    protected $guarded = [];
    public function user(){
        return $this->belongsTo('App\Models\User');
    }
/*    public function getTanggalLahirAttribute($value){
        $nama_bulan = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November","Desember"];
        $tanggal = date('j',strtotime($value));
        $bulan = date('n',strtotime($value))-1;
        $tahun = date('Y',strtotime($value));
        return $tanggal." ".$nama_bulan[$bulan]." ".$tahun;
    }*/

/*    public function getJenisKelaminAttribute($value){
        if ($value == 'L'){
            return 'Laki - Laki';
        } elseif ($value == 'P'){
            return 'Perempuan';
        }
    }*/
}

app/Http/Controllers/FrontController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FrontController extends Controller
{
    public function home(){
        $posts = Post::all();
        return view('frontend.home',['posts' => $posts]);
    }

    public function show($judul,$id){
        $artikel = Post::where('id',$id)->first();
        $jml = Post::where('id',$id)->withCount('comments')->get();
        $komentar = Comment::where('user_id',Auth::id())->get();
        $random = Post::inRandomOrder()->limit(3)->get();
/*        foreach ($artikel->comments as $komen){
            $user = Post::where('user_id',$komen->user_id)->first();
            echo $komen->komentar." komentar ini oleh : ".$user->user->name."<br>";

        }*/
    return view('frontend.show',['artikel' =>$artikel,'random' => $random,'koment'=>$artikel,'jumlah' => $jml]);
    }

    public function profil($id){
        $user = User::where('id',$id)->first();
        return view('frontend.profile',['user' => $user]);
    }
}

resources/views/frontend/home.blade.php
@extends('frontend.assets.master')
@section('konten')
    <div class="s-content">

        <div class="masonry-wrap">

            <div class="masonry">

                <div class="grid-sizer"></div>
                @forelse($posts as $post)

                    <article class="masonry__brick entry format-standard animate-this">

                        <div class="entry__text">
                            <div class="entry__header">
                                <h2 class="entry__title"><a href="{{route('front.show',['judul'=>str::slug($post->judul,'-'),'id'=>$post->id])}}">{{$post->judul}}</a></h2>
                                <div class="entry__meta">
                        <span class="entry__meta-cat">
                            <a href="category.html">{{str::limit($post->user->name,10)}}</a>
                        </span>
                                    <span class="entry__meta-date">
                            <a href="single-standard.html">{{date('d M Y',strtotime($post->created_at))}}</a>
                        </span>
                                </div>
                            </div>
                            <div class="entry__excerpt">
                                <p>
                                    {!! str::limit($post->isi, 80) !!}
                                </p>
                            </div>
                        </div>

                    </article>
                @empty
                    <div class="content__page-header entry__header">
                        <h1 class="display-1 entry__title">
                            Belum Ada Postingan, Yuk Posting!!!!!
                        </h1>
                    </div>
                @endforelse
            </div> <!-- end masonry -->

        </div> <!-- end masonry-wrap -->
{{--
        <div class="row">
            <div class="column large-full">
                <nav class="pgn">
                    <ul>
                        <li><a class="pgn__prev" href="#0">Prev</a></li>
                        <li><a class="pgn__num" href="#0">1</a></li>
                        <li><span class="pgn__num current">2</span></li>
                        <li><a class="pgn__num" href="#0">3</a></li>
                        <li><a class="pgn__num" href="#0">4</a></li>
                        <li><a class="pgn__num" href="#0">5</a></li>
                        <li><span class="pgn__num dots">…</span></li>
                        <li><a class="pgn__num" href="#0">8</a></li>
                        <li><a class="pgn__next" href="#0">Next</a></li>
                    </ul>
                </nav>
            </div>
        </div>--}}

    </div> <!-- end s-content -->

@endsection

resources/views/frontend/profile.blade.php
@extends('frontend.assets.master')
@section('konten')
    <div class="card" >
        <div class="card-header text-white bg-dark" style="font-size: 25px">
            <b >Profil "{{$user->name}}"</b>
        </div>
        <div class="card-body "style="font-size: 20px">
            <div class="card-text">
                <table class="table table-hover table-bordered">
                    <tr>
                        <td>Alamat</td>
                        <td>{{$user->profiluser->alamat}}</td>
                    </tr>
                    <tr>
                        <td>No. Telepon</td>
                        <td>{{$user->profiluser->no_telp}}</td>
                    </tr>
                    <tr>
                        <td>Tempat Lahir</td>
                        <td>{{$user->profiluser->tempat_lahir}}</td>
                    </tr>
                    <tr>
                        <td>Tanggal Lahir</td>
                        <td>{{$user->profiluser->tanggal_lahir}}</td>
                    </tr>
                    <tr>
                        <td>Jenis Kelamin</td>
                        <td>{{$user->profiluser->jenis_kelamin}}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card-footer" style="font-size: 10px">
            <a href="{{route('dashboard')}}"><i class="fas fa-tachometer-alt fa-2x"> Dashboard</i></a>
        </div>
    </div>
@endsection

resources/views/frontend/show.blade.php
@extends('frontend.assets.master')
@section('konten')
    <div class="s-content content">
        <main class="row content__page">

            <article class="column large-full entry format-standard">
                <div class="content__page-header entry__header">
                    <h1 class="display-1 entry__title">
                        {{$artikel->judul}}
                    </h1>
                    <ul class="entry__header-meta">
                        <li class="author">Oleh <a href="#0">{{$artikel->user->name}}</a></li>
                        <li class="date">{{date('d M Y',strtotime($artikel->created_at))}}</li>
                    </ul>
                </div> <!-- end entry__header -->

                <div class="entry__content">
                    <div class="drop-cap">
                        {!! $artikel->isi !!}
                    </div>
                </div> <!-- end entry content -->

                <div class="entry__related">
                    <h3 class="h2">Baca Juga</h3>

                    <ul class="related">
                        @foreach($random as $rand)
                            <article class="masonry__brick entry format-standard animate-this">
                                <div class="entry__text">
                                    <div class="entry__header">
                                        <h2 class="entry__title"><a href="{{route('front.show',['judul'=>str::slug($rand->judul,'-'),'id'=>$rand->id])}}">{{$rand->judul}}</a></h2>
                                    </div>
                                </div>

                            </article>
                        @endforeach
                    </ul>
                </div> <!-- end entry related -->

            </article> <!-- end column large-full entry-->

            <div class="comments-wrap">

                <div id="comments" class="column large-12">

                    @foreach($jumlah as $jml)
                        <h3 class="h2">{{$jml->comments_count}} Komentar</h3>
                    @endforeach

                    <!-- START commentlist -->
                    <ol class="commentlist">

                        <li class="depth-1 comment">

                            @foreach($artikel->comments as $komen)
                                <div class="comment__content">
                                    @php
                                        $user = \App\Models\Post::where('user_id',$komen->user_id)->first();
                                        echo "<div class='comment__info'>
                                        <div class='comment__author'>{$user->user->name}</div>";
                                    @endphp


                                        <div class="comment__meta">
                                            <div class="comment__time">{{$komen->created_at}}</div>
                                            <div class="comment__reply">
                                                <a class="comment-reply-link" href="#0">Reply</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="comment__text">
                                        <p>{{$komen->komentar}}</p>
                                    </div>

                                </div>
                            @endforeach

                        </li> <!-- end comment level 1 -->
                    </ol>
                    <!-- END commentlist -->

                </div> <!-- end comments -->

                <div class="column large-12 comment-respond">

                    <!-- START respond -->
                    <div id="respond">

                        <h3 class="h2">Beri Komentar </h3>
                        <form name="contactForm" id="contactForm" action="{{route('komen.store',['judul'=>str::slug($artikel->judul,'-'),'id'=>$artikel->id])}}"  method="post">
                           @csrf

                            <fieldset>
                                <div class="message form-field">
                                    <textarea name="komentar" id="cMessage" class="full-width" placeholder="Komentar"></textarea>
                                </div>

                                <button class="btn btn--primary btn-wide btn--large full-width" value="Add Comment" type="submit">Beri Komentar</button>

                            </fieldset>
                        </form> <!-- end form -->



                    </div>
                    <!-- END respond-->

                </div> <!-- end comment-respond -->

                </div> <!-- end comments-wrap -->
                </main>

                </div> <!-- end s-content -->
                @endsection