routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\ProfilUserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\CommentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontController::class,'home'])->name('home');

Route::middleware('auth')->group(function () {
    Route::get('/artikel/{judul}/{id}',[FrontController::class,'show'])->name('front.show');

    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

    Route::get('/dashboard/user/{id}/profile/edit', [ProfilUserController::class, 'edit'])->name('profil.edit')->middleware();

    Route::post('/dashboard/user/{id}/profile/edit', [ProfilUserController::class, 'store'])->name('profil.store');

    Route::put('/dashboard/user/{id}/profile/edit', [ProfilUserController::class, 'update'])->name('profil.update');
    Route::post('/artikel/{judul}/{id}',[CommentController::class,'store'])->name('komen.store');

/*    Route::get('/comments',[CommentController::class,'index'])->name('comments.index');
    Route::get('/comments/create',[CommentController::class,'showCreateForm'])->name('comments.create');*/



});



Route::get('/coba', function () {
   return view('layouts.admin-lte.master');
});

Auth::routes();
Route::get('/profil/user/edit', [ProfilUserController::class, 'edit']);
/*Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');*/
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::resource('/post', 'PostController');

resources/views/admin/dashboard.blade.php
@extends('layouts.admin-lte.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-12">
                <div class="card bg-blue">
                    <div class="card-body">
                        <div class="row text-white">
                            <div class="col"><i class="fas fa-user-cog fa-5x "></i></div>
                            <div class="col"><h4 class="font-weight-bold">Edit Profile</h4>
                                <a href="{{route('profil.edit',['id'=>Auth::id()])}}" class="btn btn-light">Edit</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-12">
                <div class="card bg-warning">
                    <div class="card-body">
                        <div class="row text-white">
                            <div class="col"><i class="fas fa-newspaper fa-5x"></i></div>
                            <div class="col"><h4 class="font-weight-bold">Postingan</h4>
                                <a href="{{route('post.index')}}" class="btn btn-light">Lihat</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')

    @if(session('notif') == 'updated')
        <script !src="">
            swal({
                title: "Berhasil!",
                text: "Data Berhasil Diupdate",
                icon: "success",
                button: "Ok",
            });</script>
        @php
        session()->forget('notif');
        @endphp
    @endif
@endpush

resources/views/admin/edit-user-profil.blade.php
@extends('layouts.admin-lte.master')
@section('content')
    <div class="card">
        <div class="card-header bg-dark">
            <b>Profil {{Auth::user()->name}}</b>
        </div>
        <div class="card-body">
            <form action="{{route('profil.store',['id'=>Auth::id()])}}" method="post" class="w-50">
                @csrf
                <div class="form-group">
                    <label for="">Nama</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{old('name')??Auth::user()->name}}">
                    @error('name') <span class="text-danger">{{$message}}</span> @enderror
                </div>
                <div class="form-group">
                    <label for="">E-Mail</label>
                    <input type="text" class="form-control" name="email" value="{{old('email')??Auth::user()->email}}" disabled>
                    @error('email') <span class="text-danger">{{$message}}</span> @enderror
                </div>
                <div class="form-group">
                    <label for="">Alamat</label>
                    <textarea name="alamat" class="form-control @error('alamat') is-invalid @enderror" id="" cols="10" rows="5">{{old('alamat')}}</textarea>
                    @error('alamat') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="">No Telp</label>
                    <input type="number" name="telp" value="{{old('telp')}}" class="form-control @error('telp') is-invalid @enderror">
                    @error('telp') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="">Tempat Lahir</label>
                    <input type="text" class="form-control @error('tempat_lahir') is-invalid @enderror" name="tempat_lahir" value="{{old('tempat_lahir')}}">
                    @error('tempat_lahir') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="">Tanggal Lahir</label>
                    <input type="date" class="form-control @error('tanggal_lahir') is-invalid @enderror" name="tanggal_lahir" value="{{old('tanggal_lahir')}}">
                    @error('tanggal_lahir') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <label for="" class="">Jenis Kelamin</label>
                <div class="form-check">
                    <input type="radio" name="jenis_kelamin" id="" class="form-check-input" value="{{old('jenis_kelamin')??'L'}}"><label for="" class="form-check-label">Pria</label>
                </div>
                <div class="form-check">
                    <input type="radio" name="jenis_kelamin" id="" class="form-check-input" value="{{old('jenis_kelamin')??'P'}}"><label for="" class="form-check-label">Wanita</label>
                </div>
                @error('jenis_kelamin') <span class="text-danger">{{$message}}</span> @enderror

        </div>
        <div class="card-footer"><button type="submit" class="btn btn-primary">Update</button>
        </div>
        </form>
    </div>
@endsection

resources/views/admin/update-user-profil.blade.php
@extends('layouts.admin-lte.master')
@section('content')
    <div class="card">
        <div class="card-header bg-dark">
            <b>Profil {{Auth::user()->name}}</b>
        </div>
        <div class="card-body">
            <form action="{{route('profil.update',['id'=>Auth::id()])}}" method="post" class="w-50">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="">Nama</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{old('name')??Auth::user()->name}}">
                    @error('name') <span class="text-danger">{{$message}}</span> @enderror
                </div>
                <div class="form-group">
                    <label for="">E-Mail</label>
                    <input type="text" class="form-control" name="email" value="{{old('email')??Auth::user()->email}}" disabled>
                    @error('email') <span class="text-danger">{{$message}}</span> @enderror
                </div>
                <div class="form-group">
                    <label for="">Alamat</label>
                    <textarea name="alamat" class="form-control @error('alamat') is-invalid @enderror" id="" cols="10" rows="5">{{old('alamat')??$profil->alamat}}</textarea>
                    @error('alamat') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="">No Telp</label>
                    <input type="number" name="telp" value="{{old('telp')??$profil->no_telp}}" class="form-control @error('telp') is-invalid @enderror">
                    @error('telp') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="">Tempat Lahir</label>
                    <input type="text" class="form-control @error('tempat_lahir') is-invalid @enderror" name="tempat_lahir" value="{{old('tempat_lahir')??$profil->tempat_lahir}}">
                    @error('tempat_lahir') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="">Tanggal Lahir</label>
                    <input type="date" class="form-control @error('tanggal_lahir') is-invalid @enderror" name="tanggal_lahir" value="{{old('tanggal_lahir')??$profil->tanggal_lahir}}">
                    @error('tanggal_lahir') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <label for="" class="">Jenis Kelamin</label>
                <div class="form-check">
                    <input type="radio" name="jenis_kelamin" id="" class="form-check-input" value="L" {{(old('jenis_kelamin')??$profil->jenis_kelamin)=='L'?'checked':''}}><label for="" class="form-check-label">Pria</label>
                </div>
                <div class="form-check">
                    <input type="radio" name="jenis_kelamin" id="" class="form-check-input" value="P" {{(old('jenis_kelamin')??$profil->jenis_kelamin)=='P'?'checked':''}}><label for="" class="form-check-label">Wanita</label>
                </div>
                @error('jenis_kelamin') <span class="text-danger">{{$message}}</span> @enderror

        </div>
        <div class="card-footer"><button type="submit" class="btn btn-primary">Update</button>
        </div>
        </form>
    </div>
@endsection